version: '3.8'

services:
    # Redis for development
    redis:
        image: redis:7-alpine
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - '6380:6379' # Use port 6380 to avoid conflict
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 3s
            retries: 5
        restart: unless-stopped

volumes:
    redis_data:
        driver: local
